<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About store' => '',
  'About us' => '',
  0 => '',
  'Add new' => '',
  'Adress' => '',
  'All products' => '',
  'Already have an account?' => '',
  'Avaible colors' => '',
  'Catalog' => '',
  'Categories' => '',
  'Change' => '',
  'Change password' => '',
  'Click to edit' => '',
  'Contact' => '',
  'Contact form' => '',
  'Contact information' => '',
  'Contact us' => '',
  'Contact with us' => '',
  'Contacts' => '',
  'Create my account' => '',
  'Create one here' => '',
  'Created' => '',
  'Delivery' => '',
  'Delivery in Ukraine' => '',
  'Delivery within relative proximity' => '',
  'Detail view' => '',
  'Don\'t have an account?' => '',
  'E-mail' => '',
  'Filtering' => '',
  'Forum' => '',
  'Full name' => '',
  'General info' => '',
  'Guest' => '',
  'Here you can change your password' => '',
  'Home' => '',
  'If you have some questions, please contact us.' => '',
  'Invalid username or password' => '',
  'Jazz-Acoustics' => '',
  'Languages' => '',
  'Log in' => '',
  'Log in here' => '',
  'Log in to your account.' => '',
  'Login' => '',
  'Login via social networks' => '',
  'Logout' => '',
  'Message' => '',
  'News' => '',
  'Oleny Stepanivny St 45, Lviv, Ukraine' => '',
  'Our office placed' => '',
  'Password' => '',
  'Phone' => '',
  'Photo' => '',
  'Please confirm your e-mail' => '',
  'Popular products' => '',
  'Products' => '',
  'Profile' => '',
  'Re-enter password' => '',
  'Register new account' => '',
  'Registration' => '',
  'Remember me next time' => '',
  'Save' => '',
  'Send' => '',
  'Sergiy' => '',
  'Settings' => '',
  'Sign in' => '',
  'Sizes' => '',
  'Skype' => '',
  'Slider' => '',
  'Sliders' => '',
  'Something went wrong, please, try again later' => '',
  'Sorry, something went wrong, try again later.' => '',
  'Specifications' => '',
  'Subject of message' => '',
  'Thank you for contacting us. We will respond to you as soon as possible.' => '',
  'User is not activated by Admin' => '',
  'Username' => '',
  'Users' => '',
  'View user: ' => '',
  'Volodymyr' => '',
  'Welcome to our store' => '',
  'Working hours' => '',
  'You registration was success, please check your e-mail for confirm link' => '',
  'Your drivers info has been changed successfuly' => '',
  'Your password has been changed successfuly' => '',
  'Контактная форма' => '',
  'Спасибі, що відвідали наш сайт.
                        Будь ласка, заповніть наступну форму,
                        щоб дізнатись більш детальну інформацію про наші продукти,
                        або для отримання зворотного зв\'язку.' => '',
);
