<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About store' => 'О магазине',
  'About us' => 'О нас',
  0 => '',
  'Add new' => 'Добавить',
  'Adress' => 'Адрес',
  'All products' => 'Все товары',
  'Already have an account?' => 'Уже зарегистрированы?',
  'Avaible colors' => 'Доступные цвета',
  'Catalog' => 'Каталог',
  'Categories' => 'Категории',
  'Change' => 'Изменить',
  'Change password' => 'Изменить пароль',
  'Click to edit' => 'Нажмите для редактирования',
  'Contact' => 'Контакты',
  'Contact form' => 'Контактная форма',
  'Contact information' => 'Контактная информация',
  'Contact us' => '',
  'Contact with us' => 'Свяжитесь с нами',
  'Contacts' => 'Контакты',
  'Create my account' => '',
  'Create one here' => '',
  'Created' => 'Создано',
  'Delivery' => 'Доставка',
  'Delivery in Ukraine' => 'Доставка по Украине',
  'Delivery within relative proximity' => 'Доставка по близости',
  'Detail view' => 'Детальней',
  'Don\'t have an account?' => 'Незарегистрированы?',
  'E-mail' => '',
  'Filtering' => 'Фильтрация',
  'Forum' => 'Форум',
  'Full name' => 'Полное имя',
  'General info' => 'Общая информация',
  'Guest' => 'Аноним',
  'Here you can change your password' => 'Здесь можно изменить пароль',
  'Home' => '',
  'If you have some questions, please contact us.' => 'Если у Вас есть вопросы, свяжитесь с нами',
  'Invalid username or password' => 'Неправильный логин или пароль',
  'Jazz-Acoustics' => '',
  'Languages' => 'Языки',
  'Log in' => 'Логин',
  'Log in here' => 'Авторизация',
  'Log in to your account.' => 'Авторизуйтесь',
  'Login' => 'Логин',
  'Login via social networks' => 'Авторизация через соц.сети',
  'Logout' => 'Выход',
  'Message' => 'Сообщение',
  'News' => 'Новости',
  'Oleny Stepanivny St 45, Lviv, Ukraine' => 'ул. Олены Степанивны. Львов, Украина',
  'Our office placed' => 'Мы тут',
  'Password' => 'Пароль',
  'Phone' => 'Телефон',
  'Photo' => 'Фото',
  'Please confirm your e-mail' => 'Подтвердите ваш електронный адрес',
  'Popular products' => 'Популярные товары',
  'Products' => 'Товары',
  'Profile' => 'Профиль',
  'Re-enter password' => 'Повторите пароль',
  'Register new account' => 'Зарегистрируйте аккаунт',
  'Registration' => 'Регистрация',
  'Remember me next time' => 'Запомнить меня',
  'Save' => 'Сохранить',
  'Send' => 'Отослать',
  'Sergiy' => 'Сергей',
  'Settings' => 'Настройки',
  'Sign in' => 'Авторизация',
  'Sizes' => 'Размеры',
  'Skype' => '',
  'Slider' => 'Слайдер',
  'Sliders' => 'Слайдеры',
  'Something went wrong, please, try again later' => 'Что-то пошло не так, попробуйте снова позже',
  'Sorry, something went wrong, try again later.' => 'Что-то пошло не так, попробуйте снова позже',
  'Specifications' => 'Спецификация',
  'Subject of message' => 'Тема сообщения',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо что связались с нами.',
  'User is not activated by Admin' => 'Пользователь не активирован администратором',
  'Username' => 'Логин',
  'Users' => 'Пользователи',
  'View user: ' => 'Просмотреть пользователя',
  'Volodymyr' => 'Владимир',
  'Welcome to our store' => 'Добро пожаловать в наш магазин',
  'Working hours' => 'Рабочие часы',
  'You registration was success, please check your e-mail for confirm link' => 'Регистрация прошла успешно, проверьте свой електронный адрес',
  'Your drivers info has been changed successfuly' => '',
  'Your password has been changed successfuly' => 'Ваш пароль успешно изменен',
  'Контактная форма' => 'Контактная форма',
  'Спасибі, що відвідали наш сайт.
                        Будь ласка, заповніть наступну форму,
                        щоб дізнатись більш детальну інформацію про наші продукти,
                        або для отримання зворотного зв\'язку.' => '',
);
