<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About store' => 'Про магазин',
  'About us' => 'Про нас',
  0 => '',
  'Add new' => 'Добавити',
  'Adress' => 'Адреса',
  'All products' => 'Всі товари',
  'Already have an account?' => 'Вже зареєстровані',
  'Avaible colors' => 'Доступні кольори',
  'Catalog' => 'Каталог',
  'Categories' => 'Категорії',
  'Change' => 'Змінити',
  'Change password' => 'Змінити пароль',
  'Click to edit' => 'Натисніть для зміни',
  'Contact' => 'Контакти',
  'Contact form' => 'Контактна форма',
  'Contact information' => 'Контактна інформація',
  'Contact us' => 'Напишіть нам',
  'Contact with us' => 'Зв\'яжіться з нами',
  'Contacts' => 'Контакти',
  'Create my account' => 'Створити аккаунт',
  'Create one here' => '',
  'Created' => 'Створено',
  'Delivery' => 'Доставка',
  'Delivery in Ukraine' => 'Доставка по Україні',
  'Delivery within relative proximity' => 'Доставка в безпосередній близькості',
  'Detail view' => 'Детальний перегляд',
  'Don\'t have an account?' => 'Не зареєстровані?',
  'E-mail' => '',
  'Filtering' => 'Фільтрація',
  'Forum' => 'Форум',
  'Full name' => 'Повне ім\'я',
  'General info' => 'Загальна інформація',
  'Guest' => 'Анонім',
  'Here you can change your password' => 'Тут ви можете змінити свій пароль',
  'Home' => 'Home',
  'If you have some questions, please contact us.' => 'Якщо ви маєте якісь запитання, напишіть нам',
  'Invalid username or password' => 'Неправильний логін або пароль',
  'Jazz-Acoustics' => '',
  'Languages' => 'Мови',
  'Log in' => 'Авторизація',
  'Log in here' => 'Авторизовуватись тут',
  'Log in to your account.' => 'Авторизуйтесь',
  'Login' => 'Авторизація',
  'Login via social networks' => 'Авторизація через соц.мережі',
  'Logout' => 'Вихід',
  'Message' => 'Повідомлення',
  'News' => 'Новини',
  'Oleny Stepanivny St 45, Lviv, Ukraine' => 'вул. Олени Степанівни 45. Львів, Україна',
  'Our office placed' => 'Ми тут',
  'Password' => 'Пароль',
  'Phone' => 'Телефон',
  'Photo' => 'Фото',
  'Please confirm your e-mail' => 'Підтвердіть ваш e-mail',
  'Popular products' => 'Популярні товари',
  'Products' => 'Товари',
  'Profile' => 'Профіль',
  'Re-enter password' => 'Повторіть',
  'Register new account' => 'Зареєструйте аккаунт',
  'Registration' => 'Реєстрація',
  'Remember me next time' => 'Запамятати себе',
  'Save' => 'Зберегти',
  'Send' => 'Надіслати',
  'Sergiy' => 'Сергій',
  'Settings' => 'Налаштування',
  'Sign in' => 'Авторизація',
  'Sizes' => 'Розміри',
  'Skype' => '',
  'Slider' => 'Слайдер',
  'Sliders' => 'Слайдери',
  'Something went wrong, please, try again later' => 'Щось пішло не так, спробуйте ще раз',
  'Sorry, something went wrong, try again later.' => 'Вибачте, щось пішло не так, спробуйте ще раз',
  'Specifications' => 'Специфікація',
  'Subject of message' => 'Тема повідомлення',
  'Thank you for contacting us. We will respond to you as soon as possible.' => 'Дякуєм, що зв\'язались з нами. Ми відповімо Вам, якомога скоріше',
  'User is not activated by Admin' => 'Користувач не активований Адміністратором',
  'Username' => 'Логін',
  'Users' => 'Користувачі',
  'View user: ' => 'Перегляд користувача',
  'Volodymyr' => 'Володимир',
  'Welcome to our store' => 'Вітаємо в нашому магазині!',
  'Working hours' => 'Робочі години',
  'You registration was success, please check your e-mail for confirm link' => 'Ваша реєстрація успішна, перевірте свій e-mail для активації акаунта',
  'Your drivers info has been changed successfuly' => '',
  'Your password has been changed successfuly' => 'Ваш пароль успішно змінений',
  'Контактная форма' => 'Контактна форма',
  'Спасибі, що відвідали наш сайт.
                        Будь ласка, заповніть наступну форму,
                        щоб дізнатись більш детальну інформацію про наші продукти,
                        або для отримання зворотного зв\'язку.' => '',
);
